<?php
return array(
	'gates'=>array(
		'green'=>array(
			'className'=>'GreenPhantomJOE'
		),
		'pokerking'=>array(
			'className'=>'PokerKing'
		),
		'haodan'=>array(
			'className'=>'HaoDan'
		),
		'tangren'=>array(
			'className'=>'Tangren'
		),
		'qianshou'=>array(
			'className'=>'Qianshou'
		),
		'lianzhong'=>array(
			'className'=>'Lianzhong'
		),
		'huangjiadp'=>array(
			'className'=>'HjDzpoker'
		),
		'sanguo'=>array(
			'className'=>'Sanguo'
		),
		'huangjia'=>array(
			'className'=>'Huangjia'
		),
		'qiangdp'=>array(
			'className'=>'Qiangdp'
		),
		'yinian'=>array(
			'className'=>'Yinian'
		),
		'gamepub'=>array(
			'className'=>'GamePub'
		),
		'chenchang'=>array(
			'className'=>'Chenchang'
		),
		'hongxiang'=>array(
			'className'=>'Hongxiang'
		),
	),
	'charges'=>array(
		'green'=>array(
			'className'=>'GreenCharge'
		),
		'pokerking'=>array(
			'className'=>'PokerCharge'
		),
		'haodan'=>array(
			'className'=>'HaodanCharge'
		),
		'tangren'=>array(
			'className'=>'TangrenCharge'
		),
		'qianshou'=>array(
			'className'=>'QianshouCharge'
		),
		'lianzhong'=>array(
			'className'=>'LianzhongCharge'
		),
		'huangjiadp'=>array(
			'className'=>'HjDzpokerCharge'
		),
		'sanguo'=>array(
			'className'=>'SanguoCharge'
		),
		'huangjia'=>array(
			'className'=>'HuangjiaCharge'
		),
		'qiangdp'=>array(
			'className'=>'QiangdpCharge'
		),
		'yinian'=>array(
			'className'=>'YinianCharge'
		),
		'gamepub'=>array(
			'className'=>'GamePubCharge'
		),
		'chenchang'=>array(
			'className'=>'ChenchangCharge'
		),
		'hongxiang'=>array(
			'className'=>'HongxiangCharge'
		),
	),
);