<?php
return array(
	'channels'=>array(
		'weibo'=>array(
			'className'=>'Weibo',
		),
		'qq'=>array(
			'className'=>'QQPlatform',
		),
		'renren'=>array(
			'className'=>'Renren',
		),
		'kaixin'=>array(
			'className'=>'Kaixin',
		),
		'douban'=>array(
			'className'=>'Douban',
		),
	),
);